version: '3.0'

name: StreamSrc
services:
  streamsrc:
    container_name: streamsrc
    hostname: streamsrc
    image: jarvisnexus/streamsrc:latest
    ports:
      - "3333:80"
    restart: unless-stopped